//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahekarusProfile.Models.CRUD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProfileDBEntities1 : DbContext
    {
        public ProfileDBEntities1()
            : base("name=ProfileDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameData> GameDatas { get; set; }

        public System.Data.Entity.DbSet<MahekarusProfile.Models.CRUD.GamesData> Games { get; set; }
    }
}
